references: &common
  working_directory: ~/sbpayment.rb
  steps:
    - checkout
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: bundle exec rspec

version: 2
jobs:
  build_ruby238:
    <<: *common
    docker:
      - image: circleci/ruby:2.3.8-browsers
  build_ruby245:
    <<: *common
    docker:
      - image: circleci/ruby:2.4.5-browsers
  build_ruby253:
    <<: *common
    docker:
      - image: circleci/ruby:2.5.3-browsers
  build_ruby260:
    <<: *common
    docker:
      - image: circleci/ruby:2.6.0-browsers

workflows:
  version: 2
  build:
    jobs:
      - build_ruby238
      - build_ruby245
      - build_ruby253
      - build_ruby260