references: &common
  working_directory: ~/sbpayment.rb
  steps:
    - checkout
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - run: bundle exec rspec

version: 2
jobs:
  build_ruby246:
    <<: *common
    docker:
      - image: circleci/ruby:2.4.6-browsers
  build_ruby255:
    <<: *common
    docker:
      - image: circleci/ruby:2.5.5-browsers
  build_ruby263:
    <<: *common
    docker:
      - image: circleci/ruby:2.6.3-browsers

workflows:
  version: 2
  build:
    jobs:
      - build_ruby246
      - build_ruby255
      - build_ruby263